//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spawn.Starfield.PluginsManager {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataDirectory {
            get {
                return ((string)(this["DataDirectory"]));
            }
            set {
                this["DataDirectory"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>BlueprintShips-Starfield.esm</string>
  <string>Constellation.esm</string>
  <string>OldMars.esm</string>
  <string>Starfield.esm</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultPlugins {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultPlugins"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>BlueprintShips-Starfield - Localization.ba2</string>\r\n  <string>OldMars - " +
            "Localization.ba2</string>\r\n  <string>OldMars - Textures.ba2</string>\r\n  <string>" +
            "Starfield - Animations.ba2</string>\r\n  <string>Starfield - DensityMaps.ba2</stri" +
            "ng>\r\n  <string>Starfield - FaceAnimation01.ba2</string>\r\n  <string>Starfield - F" +
            "aceAnimation02.ba2</string>\r\n  <string>Starfield - FaceAnimation03.ba2</string>\r" +
            "\n  <string>Starfield - FaceAnimation04.ba2</string>\r\n  <string>Starfield - FaceA" +
            "nimationPatch.ba2</string>\r\n  <string>Starfield - FaceMeshes.ba2</string>\r\n  <st" +
            "ring>Starfield - GeneratedTextures.ba2</string>\r\n  <string>Starfield - Interface" +
            ".ba2</string>\r\n  <string>Starfield - Localization.ba2</string>\r\n  <string>Starfi" +
            "eld - LODMeshes.ba2</string>\r\n  <string>Starfield - LODMeshesPatch.ba2</string>\r" +
            "\n  <string>Starfield - LODTextures.ba2</string>\r\n  <string>Starfield - Materials" +
            ".ba2</string>\r\n  <string>Starfield - Meshes01.ba2</string>\r\n  <string>Starfield " +
            "- Meshes02.ba2</string>\r\n  <string>Starfield - MeshesPatch.ba2</string>\r\n  <stri" +
            "ng>Starfield - Misc.ba2</string>\r\n  <string>Starfield - Particles.ba2</string>\r\n" +
            "  <string>Starfield - ParticlesTestData.ba2</string>\r\n  <string>Starfield - Plan" +
            "etData.ba2</string>\r\n  <string>Starfield - Shaders.ba2</string>\r\n  <string>Starf" +
            "ield - ShadersBeta.ba2</string>\r\n  <string>Starfield - Terrain01.ba2</string>\r\n " +
            " <string>Starfield - Terrain02.ba2</string>\r\n  <string>Starfield - Terrain03.ba2" +
            "</string>\r\n  <string>Starfield - Terrain04.ba2</string>\r\n  <string>Starfield - T" +
            "extures01.ba2</string>\r\n  <string>Starfield - Textures02.ba2</string>\r\n  <string" +
            ">Starfield - Textures03.ba2</string>\r\n  <string>Starfield - Textures04.ba2</stri" +
            "ng>\r\n  <string>Starfield - Textures05.ba2</string>\r\n  <string>Starfield - Textur" +
            "es06.ba2</string>\r\n  <string>Starfield - Textures07.ba2</string>\r\n  <string>Star" +
            "field - Textures08.ba2</string>\r\n  <string>Starfield - Textures09.ba2</string>\r\n" +
            "  <string>Starfield - Textures10.ba2</string>\r\n  <string>Starfield - Textures11." +
            "ba2</string>\r\n  <string>Starfield - TexturesPatch.ba2</string>\r\n  <string>Starfi" +
            "eld - Voices01.ba2</string>\r\n  <string>Starfield - Voices02.ba2</string>\r\n  <str" +
            "ing>Starfield - VoicesPatch.ba2</string>\r\n  <string>Starfield - WwiseSounds01.ba" +
            "2</string>\r\n  <string>Starfield - WwiseSounds02.ba2</string>\r\n  <string>Starfiel" +
            "d - WwiseSounds03.ba2</string>\r\n  <string>Starfield - WwiseSounds04.ba2</string>" +
            "\r\n  <string>Starfield - WwiseSounds05.ba2</string>\r\n  <string>Starfield - WwiseS" +
            "oundsPatch.ba2</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultArchives {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultArchives"]));
            }
        }
    }
}
